name: Erlang CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        otp: ['25.1.1', '26.1', '27.0']
        rebar3: ['3.23.0']

    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: ${{matrix.rebar3}}
        version-type: strict    
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, ct
